language: android

android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/5036
    - tools
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository

jdk:
  - openjdk8

install:
    # Without TERM=dumb, we get mangled output in the Travis console
    - TERM=dumb ./gradlew clean assemble

script:
    - TERM=dumb ./gradlew check

env:
  global:
    - TERM=dumb

notifications:
  email: false

#from http://blog.ansuz.nl/index.php/2014/06/01/robolectric-and-cobertura-with-gradle/
after_success:
    - ./gradlew clean cobertura coveralls -d
